# Todas as configurações do projeto em um só lugar.
# Em produção real, estes valores viriam de variáveis de ambiente.

AWS_CONFIG = {
    "endpoint_url": "http://localhost:4566",
    "region_name": "us-east-1",
    "aws_access_key_id": "test",       # LocalStack aceita qualquer valor
    "aws_secret_access_key": "test",   # LocalStack aceita qualquer valor
}

DYNAMODB_TABLE = "Orders"

# URL da fila SQS — copie o valor retornado pelo list-queues
SQS_QUEUE_URL = "http://localhost:4566/000000000000/order-notifications"

SNS_TOPIC = "order-events" # topic name — the ARN will be generated by LocalStack

SES_SENDER = "noreply@orderSystem.com"   # NOVO